#! /bin/sh

./target/release/raymarch -o movie/frame_000.png --frame-num 0
./target/release/raymarch -o movie/frame_001.png --frame-num 1
./target/release/raymarch -o movie/frame_002.png --frame-num 2
./target/release/raymarch -o movie/frame_003.png --frame-num 3
./target/release/raymarch -o movie/frame_004.png --frame-num 4
./target/release/raymarch -o movie/frame_005.png --frame-num 5
./target/release/raymarch -o movie/frame_006.png --frame-num 6
./target/release/raymarch -o movie/frame_007.png --frame-num 7
./target/release/raymarch -o movie/frame_008.png --frame-num 8
./target/release/raymarch -o movie/frame_009.png --frame-num 9
./target/release/raymarch -o movie/frame_010.png --frame-num 10
./target/release/raymarch -o movie/frame_011.png --frame-num 11
./target/release/raymarch -o movie/frame_012.png --frame-num 12
./target/release/raymarch -o movie/frame_013.png --frame-num 13
./target/release/raymarch -o movie/frame_014.png --frame-num 14
./target/release/raymarch -o movie/frame_015.png --frame-num 15
./target/release/raymarch -o movie/frame_016.png --frame-num 16
./target/release/raymarch -o movie/frame_017.png --frame-num 17
./target/release/raymarch -o movie/frame_018.png --frame-num 18
./target/release/raymarch -o movie/frame_019.png --frame-num 19
./target/release/raymarch -o movie/frame_020.png --frame-num 20
./target/release/raymarch -o movie/frame_021.png --frame-num 21
./target/release/raymarch -o movie/frame_022.png --frame-num 22
./target/release/raymarch -o movie/frame_023.png --frame-num 23
./target/release/raymarch -o movie/frame_024.png --frame-num 24
./target/release/raymarch -o movie/frame_025.png --frame-num 25
./target/release/raymarch -o movie/frame_026.png --frame-num 26
./target/release/raymarch -o movie/frame_027.png --frame-num 27
./target/release/raymarch -o movie/frame_028.png --frame-num 28
./target/release/raymarch -o movie/frame_029.png --frame-num 29
./target/release/raymarch -o movie/frame_030.png --frame-num 30
./target/release/raymarch -o movie/frame_031.png --frame-num 31
./target/release/raymarch -o movie/frame_032.png --frame-num 32
./target/release/raymarch -o movie/frame_033.png --frame-num 33
./target/release/raymarch -o movie/frame_034.png --frame-num 34
./target/release/raymarch -o movie/frame_035.png --frame-num 35
./target/release/raymarch -o movie/frame_036.png --frame-num 36
./target/release/raymarch -o movie/frame_037.png --frame-num 37
./target/release/raymarch -o movie/frame_038.png --frame-num 38
./target/release/raymarch -o movie/frame_039.png --frame-num 39
./target/release/raymarch -o movie/frame_040.png --frame-num 40
./target/release/raymarch -o movie/frame_041.png --frame-num 41
./target/release/raymarch -o movie/frame_042.png --frame-num 42
./target/release/raymarch -o movie/frame_043.png --frame-num 43
./target/release/raymarch -o movie/frame_044.png --frame-num 44
./target/release/raymarch -o movie/frame_045.png --frame-num 45
./target/release/raymarch -o movie/frame_046.png --frame-num 46
./target/release/raymarch -o movie/frame_047.png --frame-num 47
./target/release/raymarch -o movie/frame_048.png --frame-num 48
./target/release/raymarch -o movie/frame_049.png --frame-num 49
./target/release/raymarch -o movie/frame_050.png --frame-num 50
./target/release/raymarch -o movie/frame_051.png --frame-num 51
./target/release/raymarch -o movie/frame_052.png --frame-num 52
./target/release/raymarch -o movie/frame_053.png --frame-num 53
./target/release/raymarch -o movie/frame_054.png --frame-num 54
./target/release/raymarch -o movie/frame_055.png --frame-num 55
./target/release/raymarch -o movie/frame_056.png --frame-num 56
./target/release/raymarch -o movie/frame_057.png --frame-num 57
./target/release/raymarch -o movie/frame_058.png --frame-num 58
./target/release/raymarch -o movie/frame_059.png --frame-num 59
./target/release/raymarch -o movie/frame_060.png --frame-num 60
./target/release/raymarch -o movie/frame_061.png --frame-num 61
./target/release/raymarch -o movie/frame_062.png --frame-num 62
./target/release/raymarch -o movie/frame_063.png --frame-num 63
./target/release/raymarch -o movie/frame_064.png --frame-num 64
./target/release/raymarch -o movie/frame_065.png --frame-num 65
./target/release/raymarch -o movie/frame_066.png --frame-num 66
./target/release/raymarch -o movie/frame_067.png --frame-num 67
./target/release/raymarch -o movie/frame_068.png --frame-num 68
./target/release/raymarch -o movie/frame_069.png --frame-num 69
./target/release/raymarch -o movie/frame_070.png --frame-num 70
./target/release/raymarch -o movie/frame_071.png --frame-num 71
./target/release/raymarch -o movie/frame_072.png --frame-num 72
./target/release/raymarch -o movie/frame_073.png --frame-num 73
./target/release/raymarch -o movie/frame_074.png --frame-num 74
./target/release/raymarch -o movie/frame_075.png --frame-num 75
./target/release/raymarch -o movie/frame_076.png --frame-num 76
./target/release/raymarch -o movie/frame_077.png --frame-num 77
./target/release/raymarch -o movie/frame_078.png --frame-num 78
./target/release/raymarch -o movie/frame_079.png --frame-num 79
./target/release/raymarch -o movie/frame_080.png --frame-num 80
./target/release/raymarch -o movie/frame_081.png --frame-num 81
./target/release/raymarch -o movie/frame_082.png --frame-num 82
./target/release/raymarch -o movie/frame_083.png --frame-num 83
./target/release/raymarch -o movie/frame_084.png --frame-num 84
./target/release/raymarch -o movie/frame_085.png --frame-num 85
./target/release/raymarch -o movie/frame_086.png --frame-num 86
./target/release/raymarch -o movie/frame_087.png --frame-num 87
./target/release/raymarch -o movie/frame_088.png --frame-num 88
./target/release/raymarch -o movie/frame_089.png --frame-num 89
./target/release/raymarch -o movie/frame_090.png --frame-num 90
./target/release/raymarch -o movie/frame_091.png --frame-num 91
./target/release/raymarch -o movie/frame_092.png --frame-num 92
./target/release/raymarch -o movie/frame_093.png --frame-num 93
./target/release/raymarch -o movie/frame_094.png --frame-num 94
./target/release/raymarch -o movie/frame_095.png --frame-num 95
./target/release/raymarch -o movie/frame_096.png --frame-num 96
./target/release/raymarch -o movie/frame_097.png --frame-num 97
./target/release/raymarch -o movie/frame_098.png --frame-num 98
./target/release/raymarch -o movie/frame_099.png --frame-num 99
./target/release/raymarch -o movie/frame_100.png --frame-num 100
./target/release/raymarch -o movie/frame_101.png --frame-num 101
./target/release/raymarch -o movie/frame_102.png --frame-num 102
./target/release/raymarch -o movie/frame_103.png --frame-num 103
./target/release/raymarch -o movie/frame_104.png --frame-num 104
./target/release/raymarch -o movie/frame_105.png --frame-num 105
./target/release/raymarch -o movie/frame_106.png --frame-num 106
./target/release/raymarch -o movie/frame_107.png --frame-num 107
./target/release/raymarch -o movie/frame_108.png --frame-num 108
./target/release/raymarch -o movie/frame_109.png --frame-num 109
./target/release/raymarch -o movie/frame_110.png --frame-num 110
./target/release/raymarch -o movie/frame_111.png --frame-num 111
./target/release/raymarch -o movie/frame_112.png --frame-num 112
./target/release/raymarch -o movie/frame_113.png --frame-num 113
./target/release/raymarch -o movie/frame_114.png --frame-num 114
./target/release/raymarch -o movie/frame_115.png --frame-num 115
./target/release/raymarch -o movie/frame_116.png --frame-num 116
./target/release/raymarch -o movie/frame_117.png --frame-num 117
./target/release/raymarch -o movie/frame_118.png --frame-num 118
./target/release/raymarch -o movie/frame_119.png --frame-num 119
./target/release/raymarch -o movie/frame_120.png --frame-num 120
./target/release/raymarch -o movie/frame_121.png --frame-num 121
./target/release/raymarch -o movie/frame_122.png --frame-num 122
./target/release/raymarch -o movie/frame_123.png --frame-num 123
./target/release/raymarch -o movie/frame_124.png --frame-num 124
./target/release/raymarch -o movie/frame_125.png --frame-num 125
./target/release/raymarch -o movie/frame_126.png --frame-num 126
./target/release/raymarch -o movie/frame_127.png --frame-num 127
./target/release/raymarch -o movie/frame_128.png --frame-num 128
./target/release/raymarch -o movie/frame_129.png --frame-num 129
./target/release/raymarch -o movie/frame_130.png --frame-num 130
./target/release/raymarch -o movie/frame_131.png --frame-num 131
./target/release/raymarch -o movie/frame_132.png --frame-num 132
./target/release/raymarch -o movie/frame_133.png --frame-num 133
./target/release/raymarch -o movie/frame_134.png --frame-num 134
./target/release/raymarch -o movie/frame_135.png --frame-num 135
./target/release/raymarch -o movie/frame_136.png --frame-num 136
./target/release/raymarch -o movie/frame_137.png --frame-num 137
./target/release/raymarch -o movie/frame_138.png --frame-num 138
./target/release/raymarch -o movie/frame_139.png --frame-num 139
./target/release/raymarch -o movie/frame_140.png --frame-num 140
./target/release/raymarch -o movie/frame_141.png --frame-num 141
./target/release/raymarch -o movie/frame_142.png --frame-num 142
./target/release/raymarch -o movie/frame_143.png --frame-num 143
./target/release/raymarch -o movie/frame_144.png --frame-num 144
./target/release/raymarch -o movie/frame_145.png --frame-num 145
./target/release/raymarch -o movie/frame_146.png --frame-num 146
./target/release/raymarch -o movie/frame_147.png --frame-num 147
./target/release/raymarch -o movie/frame_148.png --frame-num 148
./target/release/raymarch -o movie/frame_149.png --frame-num 149
./target/release/raymarch -o movie/frame_150.png --frame-num 150
./target/release/raymarch -o movie/frame_151.png --frame-num 151
./target/release/raymarch -o movie/frame_152.png --frame-num 152
./target/release/raymarch -o movie/frame_153.png --frame-num 153
./target/release/raymarch -o movie/frame_154.png --frame-num 154
./target/release/raymarch -o movie/frame_155.png --frame-num 155
./target/release/raymarch -o movie/frame_156.png --frame-num 156
./target/release/raymarch -o movie/frame_157.png --frame-num 157
./target/release/raymarch -o movie/frame_158.png --frame-num 158
./target/release/raymarch -o movie/frame_159.png --frame-num 159
./target/release/raymarch -o movie/frame_160.png --frame-num 160
./target/release/raymarch -o movie/frame_161.png --frame-num 161
./target/release/raymarch -o movie/frame_162.png --frame-num 162
./target/release/raymarch -o movie/frame_163.png --frame-num 163
./target/release/raymarch -o movie/frame_164.png --frame-num 164
./target/release/raymarch -o movie/frame_165.png --frame-num 165
./target/release/raymarch -o movie/frame_166.png --frame-num 166
./target/release/raymarch -o movie/frame_167.png --frame-num 167
./target/release/raymarch -o movie/frame_168.png --frame-num 168
./target/release/raymarch -o movie/frame_169.png --frame-num 169
./target/release/raymarch -o movie/frame_170.png --frame-num 170
./target/release/raymarch -o movie/frame_171.png --frame-num 171
./target/release/raymarch -o movie/frame_172.png --frame-num 172
./target/release/raymarch -o movie/frame_173.png --frame-num 173
./target/release/raymarch -o movie/frame_174.png --frame-num 174
./target/release/raymarch -o movie/frame_175.png --frame-num 175
./target/release/raymarch -o movie/frame_176.png --frame-num 176
./target/release/raymarch -o movie/frame_177.png --frame-num 177
./target/release/raymarch -o movie/frame_178.png --frame-num 178
./target/release/raymarch -o movie/frame_179.png --frame-num 179
./target/release/raymarch -o movie/frame_180.png --frame-num 180
./target/release/raymarch -o movie/frame_181.png --frame-num 181
./target/release/raymarch -o movie/frame_182.png --frame-num 182
./target/release/raymarch -o movie/frame_183.png --frame-num 183
./target/release/raymarch -o movie/frame_184.png --frame-num 184
./target/release/raymarch -o movie/frame_185.png --frame-num 185
./target/release/raymarch -o movie/frame_186.png --frame-num 186
./target/release/raymarch -o movie/frame_187.png --frame-num 187
./target/release/raymarch -o movie/frame_188.png --frame-num 188
./target/release/raymarch -o movie/frame_189.png --frame-num 189
./target/release/raymarch -o movie/frame_190.png --frame-num 190
./target/release/raymarch -o movie/frame_191.png --frame-num 191
./target/release/raymarch -o movie/frame_192.png --frame-num 192
./target/release/raymarch -o movie/frame_193.png --frame-num 193
./target/release/raymarch -o movie/frame_194.png --frame-num 194
./target/release/raymarch -o movie/frame_195.png --frame-num 195
./target/release/raymarch -o movie/frame_196.png --frame-num 196
./target/release/raymarch -o movie/frame_197.png --frame-num 197
./target/release/raymarch -o movie/frame_198.png --frame-num 198
./target/release/raymarch -o movie/frame_199.png --frame-num 199
./target/release/raymarch -o movie/frame_200.png --frame-num 200
./target/release/raymarch -o movie/frame_201.png --frame-num 201
./target/release/raymarch -o movie/frame_202.png --frame-num 202
./target/release/raymarch -o movie/frame_203.png --frame-num 203
./target/release/raymarch -o movie/frame_204.png --frame-num 204
./target/release/raymarch -o movie/frame_205.png --frame-num 205
./target/release/raymarch -o movie/frame_206.png --frame-num 206
./target/release/raymarch -o movie/frame_207.png --frame-num 207
./target/release/raymarch -o movie/frame_208.png --frame-num 208
./target/release/raymarch -o movie/frame_209.png --frame-num 209
./target/release/raymarch -o movie/frame_210.png --frame-num 210
./target/release/raymarch -o movie/frame_211.png --frame-num 211
./target/release/raymarch -o movie/frame_212.png --frame-num 212
./target/release/raymarch -o movie/frame_213.png --frame-num 213
./target/release/raymarch -o movie/frame_214.png --frame-num 214
./target/release/raymarch -o movie/frame_215.png --frame-num 215
./target/release/raymarch -o movie/frame_216.png --frame-num 216
./target/release/raymarch -o movie/frame_217.png --frame-num 217
./target/release/raymarch -o movie/frame_218.png --frame-num 218
./target/release/raymarch -o movie/frame_219.png --frame-num 219
./target/release/raymarch -o movie/frame_220.png --frame-num 220
./target/release/raymarch -o movie/frame_221.png --frame-num 221
./target/release/raymarch -o movie/frame_222.png --frame-num 222
./target/release/raymarch -o movie/frame_223.png --frame-num 223
./target/release/raymarch -o movie/frame_224.png --frame-num 224
./target/release/raymarch -o movie/frame_225.png --frame-num 225
./target/release/raymarch -o movie/frame_226.png --frame-num 226
./target/release/raymarch -o movie/frame_227.png --frame-num 227
./target/release/raymarch -o movie/frame_228.png --frame-num 228
./target/release/raymarch -o movie/frame_229.png --frame-num 229
./target/release/raymarch -o movie/frame_230.png --frame-num 230
./target/release/raymarch -o movie/frame_231.png --frame-num 231
./target/release/raymarch -o movie/frame_232.png --frame-num 232
./target/release/raymarch -o movie/frame_233.png --frame-num 233
./target/release/raymarch -o movie/frame_234.png --frame-num 234
./target/release/raymarch -o movie/frame_235.png --frame-num 235
./target/release/raymarch -o movie/frame_236.png --frame-num 236
./target/release/raymarch -o movie/frame_237.png --frame-num 237
./target/release/raymarch -o movie/frame_238.png --frame-num 238
./target/release/raymarch -o movie/frame_239.png --frame-num 239
./target/release/raymarch -o movie/frame_240.png --frame-num 240
./target/release/raymarch -o movie/frame_241.png --frame-num 241
./target/release/raymarch -o movie/frame_242.png --frame-num 242
./target/release/raymarch -o movie/frame_243.png --frame-num 243
./target/release/raymarch -o movie/frame_244.png --frame-num 244
./target/release/raymarch -o movie/frame_245.png --frame-num 245
./target/release/raymarch -o movie/frame_246.png --frame-num 246
./target/release/raymarch -o movie/frame_247.png --frame-num 247
./target/release/raymarch -o movie/frame_248.png --frame-num 248
./target/release/raymarch -o movie/frame_249.png --frame-num 249
./target/release/raymarch -o movie/frame_250.png --frame-num 250
./target/release/raymarch -o movie/frame_251.png --frame-num 251
./target/release/raymarch -o movie/frame_252.png --frame-num 252
./target/release/raymarch -o movie/frame_253.png --frame-num 253
./target/release/raymarch -o movie/frame_254.png --frame-num 254
./target/release/raymarch -o movie/frame_255.png --frame-num 255
./target/release/raymarch -o movie/frame_256.png --frame-num 256
./target/release/raymarch -o movie/frame_257.png --frame-num 257
./target/release/raymarch -o movie/frame_258.png --frame-num 258
./target/release/raymarch -o movie/frame_259.png --frame-num 259
./target/release/raymarch -o movie/frame_260.png --frame-num 260
./target/release/raymarch -o movie/frame_261.png --frame-num 261
./target/release/raymarch -o movie/frame_262.png --frame-num 262
./target/release/raymarch -o movie/frame_263.png --frame-num 263
./target/release/raymarch -o movie/frame_264.png --frame-num 264
./target/release/raymarch -o movie/frame_265.png --frame-num 265
./target/release/raymarch -o movie/frame_266.png --frame-num 266
./target/release/raymarch -o movie/frame_267.png --frame-num 267
./target/release/raymarch -o movie/frame_268.png --frame-num 268
./target/release/raymarch -o movie/frame_269.png --frame-num 269
./target/release/raymarch -o movie/frame_270.png --frame-num 270
./target/release/raymarch -o movie/frame_271.png --frame-num 271
./target/release/raymarch -o movie/frame_272.png --frame-num 272
./target/release/raymarch -o movie/frame_273.png --frame-num 273
./target/release/raymarch -o movie/frame_274.png --frame-num 274
./target/release/raymarch -o movie/frame_275.png --frame-num 275
./target/release/raymarch -o movie/frame_276.png --frame-num 276
./target/release/raymarch -o movie/frame_277.png --frame-num 277
./target/release/raymarch -o movie/frame_278.png --frame-num 278
./target/release/raymarch -o movie/frame_279.png --frame-num 279
./target/release/raymarch -o movie/frame_280.png --frame-num 280
./target/release/raymarch -o movie/frame_281.png --frame-num 281
./target/release/raymarch -o movie/frame_282.png --frame-num 282
./target/release/raymarch -o movie/frame_283.png --frame-num 283
./target/release/raymarch -o movie/frame_284.png --frame-num 284
./target/release/raymarch -o movie/frame_285.png --frame-num 285
./target/release/raymarch -o movie/frame_286.png --frame-num 286
./target/release/raymarch -o movie/frame_287.png --frame-num 287
./target/release/raymarch -o movie/frame_288.png --frame-num 288
./target/release/raymarch -o movie/frame_289.png --frame-num 289
./target/release/raymarch -o movie/frame_290.png --frame-num 290
./target/release/raymarch -o movie/frame_291.png --frame-num 291
./target/release/raymarch -o movie/frame_292.png --frame-num 292
./target/release/raymarch -o movie/frame_293.png --frame-num 293
./target/release/raymarch -o movie/frame_294.png --frame-num 294
./target/release/raymarch -o movie/frame_295.png --frame-num 295
./target/release/raymarch -o movie/frame_296.png --frame-num 296
./target/release/raymarch -o movie/frame_297.png --frame-num 297
./target/release/raymarch -o movie/frame_298.png --frame-num 298
./target/release/raymarch -o movie/frame_299.png --frame-num 299
./target/release/raymarch -o movie/frame_300.png --frame-num 300
./target/release/raymarch -o movie/frame_301.png --frame-num 301
./target/release/raymarch -o movie/frame_302.png --frame-num 302
./target/release/raymarch -o movie/frame_303.png --frame-num 303
./target/release/raymarch -o movie/frame_304.png --frame-num 304
./target/release/raymarch -o movie/frame_305.png --frame-num 305
./target/release/raymarch -o movie/frame_306.png --frame-num 306
./target/release/raymarch -o movie/frame_307.png --frame-num 307
./target/release/raymarch -o movie/frame_308.png --frame-num 308
./target/release/raymarch -o movie/frame_309.png --frame-num 309
./target/release/raymarch -o movie/frame_310.png --frame-num 310
./target/release/raymarch -o movie/frame_311.png --frame-num 311
./target/release/raymarch -o movie/frame_312.png --frame-num 312
./target/release/raymarch -o movie/frame_313.png --frame-num 313
./target/release/raymarch -o movie/frame_314.png --frame-num 314
./target/release/raymarch -o movie/frame_315.png --frame-num 315
./target/release/raymarch -o movie/frame_316.png --frame-num 316
./target/release/raymarch -o movie/frame_317.png --frame-num 317
./target/release/raymarch -o movie/frame_318.png --frame-num 318
./target/release/raymarch -o movie/frame_319.png --frame-num 319
./target/release/raymarch -o movie/frame_320.png --frame-num 320
./target/release/raymarch -o movie/frame_321.png --frame-num 321
./target/release/raymarch -o movie/frame_322.png --frame-num 322
./target/release/raymarch -o movie/frame_323.png --frame-num 323
./target/release/raymarch -o movie/frame_324.png --frame-num 324
./target/release/raymarch -o movie/frame_325.png --frame-num 325
./target/release/raymarch -o movie/frame_326.png --frame-num 326
./target/release/raymarch -o movie/frame_327.png --frame-num 327
./target/release/raymarch -o movie/frame_328.png --frame-num 328
./target/release/raymarch -o movie/frame_329.png --frame-num 329
./target/release/raymarch -o movie/frame_330.png --frame-num 330
./target/release/raymarch -o movie/frame_331.png --frame-num 331
./target/release/raymarch -o movie/frame_332.png --frame-num 332
./target/release/raymarch -o movie/frame_333.png --frame-num 333
./target/release/raymarch -o movie/frame_334.png --frame-num 334
./target/release/raymarch -o movie/frame_335.png --frame-num 335
./target/release/raymarch -o movie/frame_336.png --frame-num 336
./target/release/raymarch -o movie/frame_337.png --frame-num 337
./target/release/raymarch -o movie/frame_338.png --frame-num 338
./target/release/raymarch -o movie/frame_339.png --frame-num 339
./target/release/raymarch -o movie/frame_340.png --frame-num 340
./target/release/raymarch -o movie/frame_341.png --frame-num 341
./target/release/raymarch -o movie/frame_342.png --frame-num 342
./target/release/raymarch -o movie/frame_343.png --frame-num 343
./target/release/raymarch -o movie/frame_344.png --frame-num 344
./target/release/raymarch -o movie/frame_345.png --frame-num 345
./target/release/raymarch -o movie/frame_346.png --frame-num 346
./target/release/raymarch -o movie/frame_347.png --frame-num 347
./target/release/raymarch -o movie/frame_348.png --frame-num 348
./target/release/raymarch -o movie/frame_349.png --frame-num 349
./target/release/raymarch -o movie/frame_350.png --frame-num 350
./target/release/raymarch -o movie/frame_351.png --frame-num 351
./target/release/raymarch -o movie/frame_352.png --frame-num 352
./target/release/raymarch -o movie/frame_353.png --frame-num 353
./target/release/raymarch -o movie/frame_354.png --frame-num 354
./target/release/raymarch -o movie/frame_355.png --frame-num 355
./target/release/raymarch -o movie/frame_356.png --frame-num 356
./target/release/raymarch -o movie/frame_357.png --frame-num 357
./target/release/raymarch -o movie/frame_358.png --frame-num 358
./target/release/raymarch -o movie/frame_359.png --frame-num 359
./target/release/raymarch -o movie/frame_360.png --frame-num 360
./target/release/raymarch -o movie/frame_361.png --frame-num 361
./target/release/raymarch -o movie/frame_362.png --frame-num 362
./target/release/raymarch -o movie/frame_363.png --frame-num 363
./target/release/raymarch -o movie/frame_364.png --frame-num 364
./target/release/raymarch -o movie/frame_365.png --frame-num 365
./target/release/raymarch -o movie/frame_366.png --frame-num 366
./target/release/raymarch -o movie/frame_367.png --frame-num 367
./target/release/raymarch -o movie/frame_368.png --frame-num 368
./target/release/raymarch -o movie/frame_369.png --frame-num 369
./target/release/raymarch -o movie/frame_370.png --frame-num 370
./target/release/raymarch -o movie/frame_371.png --frame-num 371
./target/release/raymarch -o movie/frame_372.png --frame-num 372
./target/release/raymarch -o movie/frame_373.png --frame-num 373
./target/release/raymarch -o movie/frame_374.png --frame-num 374
./target/release/raymarch -o movie/frame_375.png --frame-num 375
./target/release/raymarch -o movie/frame_376.png --frame-num 376
./target/release/raymarch -o movie/frame_377.png --frame-num 377
./target/release/raymarch -o movie/frame_378.png --frame-num 378
./target/release/raymarch -o movie/frame_379.png --frame-num 379
./target/release/raymarch -o movie/frame_380.png --frame-num 380
./target/release/raymarch -o movie/frame_381.png --frame-num 381
./target/release/raymarch -o movie/frame_382.png --frame-num 382
./target/release/raymarch -o movie/frame_383.png --frame-num 383
./target/release/raymarch -o movie/frame_384.png --frame-num 384
./target/release/raymarch -o movie/frame_385.png --frame-num 385
./target/release/raymarch -o movie/frame_386.png --frame-num 386
./target/release/raymarch -o movie/frame_387.png --frame-num 387
./target/release/raymarch -o movie/frame_388.png --frame-num 388
./target/release/raymarch -o movie/frame_389.png --frame-num 389
./target/release/raymarch -o movie/frame_390.png --frame-num 390
./target/release/raymarch -o movie/frame_391.png --frame-num 391
./target/release/raymarch -o movie/frame_392.png --frame-num 392
./target/release/raymarch -o movie/frame_393.png --frame-num 393
./target/release/raymarch -o movie/frame_394.png --frame-num 394
./target/release/raymarch -o movie/frame_395.png --frame-num 395
./target/release/raymarch -o movie/frame_396.png --frame-num 396
./target/release/raymarch -o movie/frame_397.png --frame-num 397
./target/release/raymarch -o movie/frame_398.png --frame-num 398
./target/release/raymarch -o movie/frame_399.png --frame-num 399

